### ISSUE TITLE
Getting regular errors from stgeorge

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#9]
Not sure what is causing this but every few days we get customers that their card fails, and the error from bank is 'check number' they try several times with no luck, they ring us up and we can pt it through our desk moto no problems, also we've had error 'under minimum transaction limit' on an order over $200.... have you heard of st george payway ? we wonder if this is meant to be the successor to webpay ??

**Comment by mitchdav** [comment]
Hi Hayden,

If you login to the merchant console, you can browse the detailed transaction report which will give you a list of every transaction attempt that hit St.George's servers, and this will give you as much diagnostic information as is possible to resolve the issue. From this report you can find all of the transactions that were declined, and then further information about the specific error code and text.

If this is happening often, it would be best to contact St.George directly and quote the transaction numbers from that report, where they should be able to tell you specifically what the problem was.

We have not seen the "under minimum transaction limit" error, so I can't advise on that, other than to check what the report says was the charge received by their system so you can verify that the code (either yours or mine) is providing this to St.George correctly.

I haven't looked into Payway (we will soon be moving to Stripe anyway), but I'm sure you can ask the bank for more information about it.

Cheers.

**Comment by hayden-t** [comment]
The merchant console does not give any different error message/code other than that reported by the api.
St george hve just blamed the clients bank. We will likely just have to try an alternative processor.

**Comment by mitchdav** [comment]
We have had similar interactions with them at different times, and yes it can be frustrating to hear that they can't make additional information available in some cases.

Best of luck with the alternative options!
